export const medicationList = [
  "Sulfonylurea",
  "Alpha-glucosidase Inhibitor",
  "SGLT2 Inhibitor",
  "Thiazolidinedione",
  "Insulin",
  "Meglitinide",
  "Metformin",
  "Biguanide",
  "Glitazone",
  "Exenatide",
  "Semaglutide",
  "Alogliptin",
  "Amylin Analog",
  "Glipizide",
  "Incretin-based Therapies",
  "Lixisenatide",
  "Dopamine Agonist",
  "Glucobay",
  "Jardiance",
  "Bile Acid Sequestrant",
];
