// const fakeUser = {
//   username: "johndoe001",
//   email: "johndoe001@email.com",
//   password: "fakePassword",
//   first_name: "John",
//   last_name: "Doe",
//   country: "Singapore",
//   age: 25,
//   gender: "M",
//   weight_kg: 65,
//   height_kg: 170,
//   diabetes_type: "Type 1",
//   medication_list: [],
//   caloric_goal_kcal: 2000,
//   hyper_mg_dl: 180,
//   hypo_mg_dl: 70,
//   target_lower_mg_dl: 80,
//   target_upper_mg_dl: 130,
// };
